### ISSUE TITLE
Have reduce clone by default?

### ISSUE THREAD

**Issue by jsoverson** [shapesecurity/shift-reducer-js#18]
Right now reduce({}, program) throws 'undefined is not a function' errors. Should the default behavior simply return `state` if a reduction function is not found? This would obviate the need to inherit from CloneReducer and the CloneReducer itself could be removed making it more obvious how to get started.

**Comment by michaelficarra** [comment]
I like the way you're thinking, but it would be surprising for a reducer that is missing a function to behave like the "identity reducer" when it encounters a node of that type. Instead, I agree we _should_ have default reducing functions, but those functions should still throw, just with more descriptive errors than "undefined is not a function". They should throw an error with a message like "encountered a LiteralNullExpression while reducing using a reducer that has not defined a reduction function for LiteralNullExpression". Obviously we can find something a bit more terse and similarly descriptive.

**Comment by michaelficarra** [comment]
Fixed by #21.
