### ISSUE TITLE
Question for reduceCallExpression in nested structure

### ISSUE THREAD

**Issue by ash0080** [shapesecurity/shift-reducer-js#47]
For example
```
(function(){
  function sum(a,b) {
    return a+b  
  }
s[sum(1,2)]
})()
```

try to replace sum(1,2)  with 3 using a lazyCloneReducer
but in a nested structure  like above,
the updated nodes will be override by outer node later :(

Any helps?  like if the AST nodes could be updated every step? or the reducer could be run from tree root to leaves?

**Comment by ash0080** [comment]
I think this issue is not specific to a closure but all nested structures

**Comment by bakkot** [comment]
The LazyCloneReducer methods get two arguments: the original node and an object containing the children of the new node (not the new node itself; you shouldn't return this object). If you are returning something new, you should base it on the second argument, not the first. If aren't trying to return something different, you should defer to the super method.

For example:

```js
const { parseScript } = require('shift-parser');
const { default: codegen } = require('shift-codegen');
const { reduce, LazyCloneReducer } = require('shift-reducer');
const Shift = require('shift-ast/checked');

class ReplaceCallReducer extends LazyCloneReducer {
  reduceCallExpression(node, newNode) {
    if (newNode.callee.type === 'IdentifierExpression' && newNode.callee.name === 'example') {
      const newName = new Shift.IdentifierExpression({ name: 'foobar' });
      return new Shift.CallExpression({ callee: newName, arguments: newNode.arguments });
    } else if (newNode.callee.type === 'IdentifierExpression' && newNode.callee.name === 'sum' && newNode.arguments.every(a => a.type === 'LiteralNumericExpression')) {
      const sum = newNode.arguments.reduce((acc, n) => acc + n.value, 0);
      return new Shift.LiteralNumericExpression({ value: sum });
    }
    return super.reduceCallExpression(node, newNode);
  }
}


const original = parseScript(`
  untouched( example( example(sum(1, 2)), sum(2, 3, 4, 5) ) ); 
`);

const transformed = reduce(new ReplaceCallReducer(), original);

console.log(codegen(transformed));
```

outputs `untouched(foobar(foobar(3),14))`

**Comment by ash0080** [comment]
There is something wrong with the 'node.arguments' for the npm installed version
cuz the newNode is 
```
{type:<String>, _arguments:<Array>}
```
but if using an auto spread as in Example , { callee, arguments: _arguments }, arguments will be casted to an object with keys 1,2...n but not an array yet, 

In short, there is something wrong
so, should use node._arguments for instead, but there are still issues.

In short, no matter if or not using super call, in some extreme situation ( haven't catch it yet， will update if I can ), will throw an 

> TypeError: Cannot read property 'length' of undefined
>     at CallExpressionReducer.reduceNewExpression (/deobfuscator/node_modules/shift-reducer/dist/lazy-clone-reducer.js:668:74)

but line 668  is inside reduceNewExpression
And for simple AST, it works, but now I am working on a deobfuscator tool, so the use case is much more complex
 
even simplify the reducer without any override as below

```
class CallExpressionReducer extends LazyCloneReducer{}
```
This error is still there, Thought it's Incredible，but it happened :(


update, done with override the methods with fix.
I think all problem is because the _arguments cast
```
var callee = _ref15.callee,
          _arguments = _ref15.arguments;

// but 'arguments' is undefined
```

update, when using reduceConditionalExpression, I get
```
> deobfuscator/node_modules/shift-reducer/dist/director.js:120
>     return reducer.reduceCompoundAssignmentExpression(node, { binding: this[node.binding.type](reducer, node.binding), expression: this[node.expression.type](reducer, node.expression) });
>                                                                                                                                                         ^
> 
> TypeError: Cannot read property 'type' of undefined
```

**Comment by bakkot** [comment]
> but if using an auto spread as in Example , { callee, arguments: _arguments }, arguments will be casted to an object with keys 1,2...n but not an array yet,

That code creates a variable named `_arguments`, not `arguments`. [`arguments`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/arguments) is a different thing.

> even simplify the reducer without any override as below
> class CallExpressionReducer extends LazyCloneReducer{}
> This error is still there, Thought it's Incredible，but it happened :(

Can you provide an example?


> when using reduceConditionalExpression, I get
> TypeError: Cannot read property 'type' of undefined

That's because ConditionalExpressions [do not have an `expression` property](https://github.com/shapesecurity/shift-spec/blob/96a97215fbfb4f6bfbec8ac0e8149b8c6b72ebeb/spec.idl#L349-L353).

Also, can you provide the code you're working with? It's hard for me to tell what's wrong without looking at it.

PS: 

> now I am working on a deobfuscator tool

You may be interested in [unminify](https://github.com/shapesecurity/unminify), which is a deobfuscation tool written using the Shift suite. [Here's](https://blog.shapesecurity.com/2018/03/02/introducing-unminify/) a blog post introducing it.

**Comment by ash0080** [comment]
> const sum = newNode.arguments.reduce((acc, n) => acc + n.value, 0);

yes, but only _arguments, that's the point
and in source code
```
var callee = _ref15.callee,
      _arguments = _ref15.arguments;
// should be  _ref15._arguments ???
```
After I override the code with fix, at least, all Errors on ReplaceCall and reduceNewExpression gone

> Can you provide an example?

 [F5MangledCode](http://mcn.ssgdfm.com/TSPD/08246695e1ab2000e8e60102d8b1a7c980ed97f086d01c204f1f61d7bea67777c76413f4c957035e?type=10)
I think the link works in several hours, plz save it locally

> That's because ConditionalExpressions do not have an expression property.

The error actually triggered on reduceCompoundAssignmentExpression, but I did nothing on that 
node type, that's the weird part..and even I do nothing  but just super call（to return the original node) in ConditionalExpressions , the error still thrown

> You may be interested in unminify, which is a deobfuscation tool written using the Shift suite. Here's a blog post introducing it

sure, I use it at the last step of my process : )

**Comment by bakkot** [comment]
> The error actually triggered on reduceCompoundAssignmentExpression, but I did nothing on that node type, that's the weird part.

Can you link or paste the code you're writing which triggers this?

The most likely thing, I would guess, is that you're mutating the original tree. Most of the reducers don't work right if you do that. You have to return new things instead of mutating the original one.

**Comment by ash0080** [comment]
the minimal test with Error
```
module.exports = sourceCode => {
  class LiteralConditionReducer extends LazyCloneReducer {
    reduceConditionalExpression (node, newNode) {
      super.reduceConditionalExpression(node, newNode)
    }
  }

  const { tree, locations } = parseScriptWithLocation(sourceCode)
  let literalConditionReduce = memoize(thunkify(new LiteralConditionReducer))
  let updated = thunkedReduce(literalConditionReduce, tree)
}

const fs = require('fs')
const deobfu = require('./util/minimal')
const sourceCode = fs.readFileSync('./data/online.js').toString()

deobfu(sourceCode)

```

reduceCompoundAssignmentExpression Error should happen after override  reduceConditionalExpression, the other errors happens directly.

**Comment by bakkot** [comment]
You need to `return` the result of calling `super`:

> reduceConditionalExpression (node, newNode) {
>   **return** super.reduceConditionalExpression(node, newNode)
> }

**Comment by ash0080** [comment]
> You need to return the result of calling super:

seriously?  super.call includes return 

Anyway, using return doesn't change anything,  the errors still there

**Comment by bakkot** [comment]
> I don't think so, cuz super.call return things

That doesn't get propagated. You do.

But there's also a bug in thunkify. Thanks for the code sample. I'll get it fixed and publish a new release.

**Comment by ash0080** [comment]
> But there's also a bug in thunkify. Thanks for the code sample. I'll get it fixed and publish a new release.

👍 thx,  cuz I overrode all reducers with fix in practice code , so dosen't realize it.
but I tested without thunked before, the errors still happen, plz test it

**Comment by bakkot** [comment]
Fix is published as v4.4.1. Sorry for the delay.

> but I tested without thunked before, the errors still happen, plz test it

Can you give another sample? The minimal test you posted above works for me now.

**Comment by ash0080** [comment]
reduceBinaryExpression (node, newNode)

BinaryExpression like （false,1)
the newNode.operator === undefined but not ',' as AST.BinaryExpression defined

**Comment by bakkot** [comment]
Yeah, that's expected. It's not actually a node object. You have to pass it to the corresponding super method to get the properties which aren't themselves nodes added.

You can read the operator from the original node, if you need it.

**Comment by ash0080** [comment]
@bakkot 

Great, no other problem found now, For me the deobfuscator part is almost done and works fine ；）
The scope and reducer part is much much better than esprima, thanks for your great work

**Comment by bakkot** [comment]
I'd love to see your project if you end up releasing it publicly!

**Comment by bakkot** [comment]
I'm going to close this for the moment, but please open a new issue if you run into other problems.
