### ISSUE TITLE
Add simplified usage, documentation & benefits.

### ISSUE THREAD

**Issue by jsoverson** [shapesecurity/shift-reducer-js#9]
The concerns [here](https://twitter.com/zerusski/status/547772099117744129) are relevant & simply linking to usage isn't enough to help people get started.

**Comment by michaelficarra** [comment]
Linking to the usage examples was a quick way to get everything minimally documented. For this library in particular, I think a tutorial would be more useful than intricate, javadoc-style API documentation.

**Comment by emattson** [comment]
@michaelficarra @jsoverson should we put that blog post from a while ago into the readme?

**Comment by michaelficarra** [comment]
@emattson Unfortunately, that's a bit outdated with the new major version of the reducer. The same concepts in the examples apply, though.
